name: A workflow for converting my CV to PDF 
on: push

jobs:
  build:
    name: Convert markdown to PDF 
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
      uses: ./action-a
    - name: Create PDF
      uses: actions/upload-artifact@v1
      with:
          name: cv
          path: output/cv.pdf

    
