name: A workflow for converting my CV to PDF 
on: push

jobs:
  build:
    name: Convert markdown to PDF 
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Build CV as PDF
      uses: ./action-a
    - name: Create Finnish PDF as artifact
      uses: actions/upload-artifact@v1
      with:
          name: Finnish CV
          path: output/cv.pdf
    - name: Create English PDF as artifact
      uses: actions/upload-artifact@v1
      with:
          name: English CV
          path: output/cv_en.pdf
    - name: GitHub Releases
      uses: fnkr/github-action-ghr@v1.3

    
