name: A workflow for converting my CV to PDF 
on: push

jobs:
  build:
    name: Convert markdown to PDF 
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Build CV as PDF
      uses: ./action-a
    - name: Create CV PDF as artifact
      uses: actions/upload-artifact@v2
      with:
          name: CV
          path: |
            output/cv_en.pdf
            output/cv.pdf

